<?xml version='1.0' encoding='utf-8'?>
<plist version="1.0">
    <important_information>
        <![CDATA[
    This file has been converted from https://github.com/renpy/vscode-language-renpy/blob/master/syntaxes/renpy.atl.tmLanguage.json.
    If you want to provide a fix or improvement, please create a pull request against the original repository.
        ]]>
    </important_information>
	<dict>
		<key>information_for_contributors</key>
		<array>
			<string>Please remeber to regenerate the ts token patterns using the 'syntax-to-token-pattern.py' python script</string>
		</array>
		<key>fileTypes</key>
        <array>
        	<string>rpy</string>
        </array>
		<key>$schema</key>
		<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
		<key>name</key>
		<string>Ren'Py ATL</string>
		<key>scopeName</key>
		<string>source.renpy.atl</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#atl</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>atl</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#atl-syntax-and-semantics</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#conditionals</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-keywords</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-warper</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-blocks</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-simple-expression</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-event</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-on</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-function</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-fallback</string>
					</dict>
				</array>
			</dict>
			<key>atl-build-in-properties</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#list-of-transform-properties</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>Special manipulation keywords</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:(warp)|(circles)|(clockwise)|(counterclockwise))\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.warp.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.circles.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>keyword.clockwise.renpy</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>keyword.counterclockwise.renpy</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>position props (int, absolute, or a float)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xpos|ypos|xanchor|yanchor|xcenter|ycenter|radius)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>position pair props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:pos|anchor|xycenter|around|alignaround|matrixanchor)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>float props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xalign|yalign|zoom|xzoom|yzoom|alpha|additive|angle|delay|events|zpos)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>float pair props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:align|knot)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>int props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xoffset|yoffset|xtile|ytile)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>int pair props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:offset)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>boolean props</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:rotate_pad|transform_anchor|nearest|crop_relative|subpixel|zzoom)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#float' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:rotate|xpan|ypan|blur)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#position' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xsize|ysize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int, int, int\)' | '\(float, float, float, float\)' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:crop)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int\)' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:corner1|corner2)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(position, position\)' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xysize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#string' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:fit)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int\)' | None)</string>
						<key>name</key>
						<string>invalid.deprecated.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:size|maxsize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#Matrix' | '#MatrixColor' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:matrixcolor)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#Matrix' | '#TransformMatrix' | None)</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:matrixtransform)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#bool' | '#float' | '\(float, float, float\)')</string>
						<key>name</key>
						<string>support.type.property-name.transform.renpy entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:perspective)\b</string>
					</dict>
				</array>
			</dict>
			<key>atl-simple-expression</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#renpy-only-expressions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-build-in-properties</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#member-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#illegal-operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#curly-braces</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#item-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#list</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#odd-function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#round-braces</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-functions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-types</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-exceptions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#magic-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#special-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#illegal-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#special-variables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#ellipsis</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#punctuation</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#line-continuation</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Tokenize identifiers</string>
						<key>name</key>
						<string>variable.name.python</string>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy#whitespace</string>
					</dict>
				</array>
			</dict>
			<key>atl-expression</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#expression-statement</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atl-simple-expression</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>\b(with)\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.with.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-simple-expression</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#expression</string>
					</dict>
				</array>
			</dict>
			<key>atl-keywords</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#animation-statement</string>
						<key>match</key>
						<string>^[ \t]*(animation)\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.animation.renpy</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#pass-statement</string>
						<key>match</key>
						<string>^[ \t]*(pass)\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.flow.pass.renpy</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#repeat-statement and https://www.renpy.org/doc/html/atl.html#time-statement</string>
						<key>begin</key>
						<string>^[ \t]*(?:(repeat)|(time)|(pause))\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.flow.repeat.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.control.flow.time.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>keyword.control.flow.pause.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-simple-expression</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#expression-statement</string>
						<key>contentName</key>
						<string>meta.atl.with.renpy</string>
						<key>begin</key>
						<string>^[ \t]*(with)\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.with.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-simple-expression</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#contains-statement</string>
						<key>contentName</key>
						<string>meta.atl.contains.renpy</string>
						<key>begin</key>
						<string>^[ \t]*(contains)\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.flow.contains.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-expression</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>comment</key>
						<string>TODO: This is a temporary include until we have proper support for all ATL keywords</string>
						<key>include</key>
						<string>source.renpy#keywords</string>
					</dict>
				</array>
			</dict>
			<key>atl-blocks</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>See https://www.renpy.org/doc/html/atl.html</string>
						<key>contentName</key>
						<string>meta.atl.block.renpy</string>
						<key>begin</key>
						<string>^([ \t]+)?(?:(block)|(parallel)|(contains))\b[ \t]*(:)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.whitespace.leading.block.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.block.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>keyword.parallel.renpy</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>keyword.contains.renpy</string>
							</dict>
							<key>5</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>comment</key>
						<string>https://www.renpy.org/doc/html/atl.html#choice-statement</string>
						<key>contentName</key>
						<string>meta.atl.choice.block.renpy</string>
						<key>begin</key>
						<string>^([ \t]+)?(choice)\b[ \t]*(.+)?(:)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.whitespace.leading.block.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.choice.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#atl-simple-expression</string>
									</dict>
								</array>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>atl-build-in-events</key>
			<dict>
				<key>comment</key>
				<string>Pre-defined events (https://www.renpy.org/doc/html/atl.html#external-events)</string>
				<key>name</key>
				<string>support.function.event.renpy</string>
				<key>match</key>
				<string>\b(?&lt;!\.)(?:start|show|replace|hide|replaced|update|hover|idle|selected_hover|selected_idle)\b</string>
			</dict>
			<key>atl-event-name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-possible-callables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-build-in-events</string>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.function.event.renpy meta.function-call.generic.renpy</string>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
					</dict>
				</array>
			</dict>
			<key>atl-event-def-name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-possible-callables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-build-in-events</string>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.function.event.def.renpy</string>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
					</dict>
				</array>
			</dict>
			<key>atl-event</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#event-statement</string>
				<key>name</key>
				<string>meta.atl.event.renpy</string>
				<key>match</key>
				<string>^[ \t]*(event)\b[ \t]*\b([[:alpha:]_]\w*)\b</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.event.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-event-name</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>atl-on</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#on-statement</string>
				<key>contentName</key>
				<string>meta.atl.on.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(on)\b[ \t]*(.+)?(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.block.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.on.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-event-name</string>
							</dict>
							<dict>
								<key>match</key>
								<string>[ \t]*,[ \t]*</string>
								<key>name</key>
								<string>punctuation.separator.parameters.renpy</string>
							</dict>
							<dict>
								<key>include</key>
								<string>source.renpy#comments</string>
							</dict>
						</array>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atl</string>
					</dict>
				</array>
			</dict>
			<key>atl-function</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/atl.html#function-statement</string>
				<key>name</key>
				<string>meta.atl.function.renpy</string>
				<key>match</key>
				<string>^[ \t]*(function)\b[ \t]*\b([[:alpha:]_]\w*)\b</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.function.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.renpy.python#builtin-possible-callables</string>
							</dict>
							<dict>
								<key>name</key>
								<string>entity.name.function.atl-function.renpy meta.function-call.generic.renpy</string>
								<key>match</key>
								<string>\b([[:alpha:]_]\w*)\b</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>atl-build-in-warpers</key>
			<dict>
				<key>comment</key>
				<string>Pre-defined warpers (https://www.renpy.org/doc/html/atl.html#warpers)</string>
				<key>name</key>
				<string>support.function.renpy</string>
				<key>match</key>
				<string>\b(?&lt;!\.)(?:linear|ease|easein|easeout|ease_back|ease_bounce|ease_circ|ease_cubic|ease_elastic|ease_expo|ease_quad|ease_quart|ease_quint|easein_back|easein_bounce|easein_circ|easein_cubic|easein_elastic|easein_expo|easein_quad|easein_quart|easein_quint|easeout_back|easeout_bounce|easeout_circ|easeout_cubic|easeout_elastic|easeout_expo|easeout_quad|easeout_quart|easeout_quint)\b</string>
			</dict>
			<key>atl-warper-name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-possible-callables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-build-in-warpers</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atl-build-in-properties</string>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.function.warper.renpy meta.function-call.generic.renpy</string>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
					</dict>
				</array>
			</dict>
			<key>atl-warper-broken</key>
			<dict>
				<key>comment</key>
				<string>TODO: This doesn't work right now, we can't assume all identifiers are warpers</string>
				<key>name</key>
				<string>meta.atl.warper.renpy</string>
				<key>begin</key>
				<string>(?&lt;=^[ \t]*)([[:alpha:]_]\w*)\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-warper-name</string>
							</dict>
						</array>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=[ \t]*#)|$</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atl-simple-expression</string>
					</dict>
				</array>
			</dict>
			<key>atl-warper</key>
			<dict>
				<key>comment</key>
				<string>(TODO: For now we only support build-in warper highlighting) https://www.renpy.org/doc/html/atl.html#warpers</string>
				<key>name</key>
				<string>meta.atl.warper.renpy</string>
				<key>begin</key>
				<string>(?&lt;=^[ \t]*)(linear|ease|easein|easeout|ease_back|ease_bounce|ease_circ|ease_cubic|ease_elastic|ease_expo|ease_quad|ease_quart|ease_quint|easein_back|easein_bounce|easein_circ|easein_cubic|easein_elastic|easein_expo|easein_quad|easein_quart|easein_quint|easeout_back|easeout_bounce|easeout_circ|easeout_cubic|easeout_elastic|easeout_expo|easeout_quad|easeout_quart|easeout_quint)\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atl-warper-name</string>
							</dict>
						</array>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=[ \t]*#)|$</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atl-simple-expression</string>
					</dict>
				</array>
			</dict>
			<key>atl-fallback</key>
			<dict>
				<key>comment</key>
				<string>TODO: This is a temp fix for missing pattern references</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#base-patterns</string>
					</dict>
				</array>
			</dict>
			<key>transform</key>
			<dict>
				<key>contentName</key>
				<string>meta.transform.block.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(transform)\b[ \t]*(.*)?(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.transform.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>name</key>
								<string>variable.name.transform.renpy</string>
								<key>match</key>
								<string>\b([[:alpha:]_]\w*)\b</string>
							</dict>
						</array>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.atl.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atl</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>