<?xml version='1.0' encoding='utf-8'?>
<plist version="1.0">
    <important_information>
        <![CDATA[
    This file has been converted from https://github.com/renpy/vscode-language-renpy/blob/master/syntaxes/renpy.screen.tmLanguage.json.
    If you want to provide a fix or improvement, please create a pull request against the original repository.
        ]]>
    </important_information>
	<dict>
		<key>information_for_contributors</key>
		<array>
			<string>Please remeber to regenerate the ts token patterns using the 'syntax-to-token-pattern.py' python script</string>
		</array>
		<key>fileTypes</key>
        <array>
        	<string>rpy</string>
        </array>
		<key>$schema</key>
		<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
		<key>name</key>
		<string>Ren'Py Screen</string>
		<key>scopeName</key>
		<string>source.renpy.screen</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#screen-language</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>builtin-screens</key>
			<dict>
				<key>name</key>
				<string>support.function.builtin.screen.renpy</string>
				<key>match</key>
				<string>(?&lt;!\.)\b(?:start|quit|after_load|splashscreen|before_main_menu|main_menu|after_warp|hide_windows)\b</string>
			</dict>
			<key>screen-def-name</key>
			<dict>
				<key>comment</key>
				<string>TODO: Should combine this with label-def-name</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-possible-callables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-screens</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?&lt;=^|[ \t])(\b(?:[a-zA-Z_]\w*)\b)?(\.)?(\b(?:[a-zA-Z_]\w*)\b)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.period.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.renpy</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>
			<key>screen-build-in-properties</key>
			<dict>
				<key>comment</key>
				<string>These are the ATL keywords, will need to fix this later</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>Special manipulation keywords</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:(warp)|(circles)|(clockwise)|(counterclockwise))\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.warp.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.circles.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>keyword.clockwise.renpy</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>keyword.counterclockwise.renpy</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>Special manipulation keywords</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(key|input|(image)?button|grid|auto|mousearea|side|timer|[vh]?bar|viewport|scrollbars|mousewheel|vpgrid|imagemap)\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.other.renpy</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>Random props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:[xy]padding|area|(un)?hovered|draggable|cols|spacing|side_[xy]align)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>position props (int, absolute, or a float)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xpos|ypos|xanchor|yanchor|xcenter|ycenter|radius)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>position pair props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:pos|anchor|xycenter|around|alignaround|matrixanchor)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>float props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xalign|yalign|zoom|xzoom|yzoom|alpha|additive|angle|delay|events|zpos)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>float pair props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:align|knot)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>int props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xoffset|yoffset|xtile|ytile|size)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>int pair props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:offset)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>boolean props</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:rotate_pad|transform_anchor|nearest|crop_relative|subpixel|zzoom)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#float' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:rotate|xpan|ypan|blur)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#position' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xsize|ysize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int, int, int\)' | '\(float, float, float, float\)' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:crop)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int\)' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:corner1|corner2)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(position, position\)' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:xysize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#string' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:fit)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('\(int, int\)' | None)</string>
						<key>name</key>
						<string>invalid.deprecated.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:size|maxsize)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#Matrix' | '#MatrixColor' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:matrixcolor)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#Matrix' | '#TransformMatrix' | None)</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:matrixtransform)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>('#bool' | '#float' | '\(float, float, float\)')</string>
						<key>name</key>
						<string>entity.name.tag.css.transform.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:perspective)\b</string>
					</dict>
				</array>
			</dict>
			<key>screen-simple-expression</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#renpy-only-expressions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-build-in-properties</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#member-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#illegal-operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#curly-braces</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#item-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#list</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#odd-function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#round-braces</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-functions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-types</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#builtin-exceptions</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#magic-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#special-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#illegal-names</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#special-variables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#ellipsis</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#punctuation</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy.python#line-continuation</string>
					</dict>
				</array>
			</dict>
			<key>screen-keywords</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/screens.html#screen-statement</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>contentName</key>
						<string>meta.screen.sensitive.renpy</string>
						<key>begin</key>
						<string>(?&lt;=^[ \t]*)(sensitive)\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.sensitive.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#screen-simple-expression</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.other.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:modal|sensitive|tag|zorder|variant|layer|roll_forward|text)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.other.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:style|style_group|style_prefix)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.other.renpy</string>
						<key>match</key>
						<string>\b(?&lt;!\.)(?:has|vbox|hbox|label|add|xfill)\b</string>
					</dict>
				</array>
			</dict>
			<key>screen-frame</key>
			<dict>
				<key>contentName</key>
				<string>meta.screen.frame.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(frame)\b[ \t]*(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.block.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.frame.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#screen-language</string>
					</dict>
				</array>
			</dict>
			<key>screen-window</key>
			<dict>
				<key>contentName</key>
				<string>meta.screen.window.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(window)\b[ \t]*(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.block.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.window.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#screen-language</string>
					</dict>
				</array>
			</dict>
			<key>screen-text</key>
			<dict>
				<key>contentName</key>
				<string>meta.screen.text.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(text)\b[ \t]*(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.block.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.text.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>meta.screen.text.renpy</string>
						<key>contentName</key>
						<string>meta.atl-block.renpy</string>
						<key>begin</key>
						<string>^([ \t]+)?(text)\b[ \t]*([a-zA-Z_0-9 ]*)(:)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.whitespace.leading.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.text.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>entity.name.type.text.renpy</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.atl.begin.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.renpy.atl</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.screen.text.renpy</string>
						<key>begin</key>
						<string>(?&lt;=^[ \t]*)(text)\b[ \t]*</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.text.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(?=\b(at)\b|#|=)|$</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.renpy#strings</string>
							</dict>
							<dict>
								<key>match</key>
								<string>\b(?:[a-zA-Z_0-9]+)\b[ \t]*</string>
								<key>name</key>
								<string>entity.name.type.text.renpy</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>source.renpy#at-statement</string>
					</dict>
				</array>
			</dict>
			<key>screen-box</key>
			<dict>
				<key>contentName</key>
				<string>meta.screen.block.renpy</string>
				<key>begin</key>
				<string>^([ \t]+)?(?:(vbox)|(hbox))\b[ \t]*(?:.*?)(:)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.whitespace.leading.block.renpy</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.vbox.renpy</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>keyword.hbox.renpy</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#screen-language</string>
					</dict>
				</array>
			</dict>
			<key>screen</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>See https://www.renpy.org/doc/html/screens.html</string>
						<key>contentName</key>
						<string>meta.screen.block.renpy</string>
						<key>begin</key>
						<string>^([ \t]+)?(screen)\b[ \t]*(.*?)(:)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.whitespace.leading.block.renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>storage.type.function.renpy</string>
							</dict>
							<key>3</key>
							<dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#screen-def-name</string>
									</dict>
									<dict>
										<key>include</key>
										<string>source.renpy.python#parameters</string>
									</dict>
									<dict>
										<key>include</key>
										<string>source.renpy#invalid-token</string>
									</dict>
								</array>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.renpy</string>
							</dict>
						</dict>
						<key>end</key>
						<string>^(?=(?!\1)[ \t]*[^\s#]|\1[^\s#])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#screen-language</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>screen-fallback</key>
			<dict>
				<key>comment</key>
				<string>TODO: This is a temp fix for missing pattern references</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#base-patterns</string>
					</dict>
				</array>
			</dict>
			<key>screen-language</key>
			<dict>
				<key>comment</key>
				<string>https://www.renpy.org/doc/html/screens.html#screen-language</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>source.renpy#conditionals</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-frame</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-window</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-box</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-text</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-keywords</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-simple-expression</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#screen-fallback</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>